version: '3.3'

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:${DB_PASSWORD}@db:5432/${DB_NAME}
    # volumes:
    #       - .:/app
    # command: air ./cmd/main.go -b 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:alpine
    user: postgres
    environment:
      # - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGUSER= postgres
      - DATABASE_URL=${DB_URL}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: