version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    # command: air ./cmd/main.go -b 0.0.0.0
    environment:
      - GO_ENV=development
  db:
    image: postgres:alpine
    user: postgres
    environment:
      # - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGUSER= postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: