FROM golang:1.23.3

WORKDIR /app

RUN git config --global --add safe.directory ~/git/go-workspace/github.com/obiewalker/nomada-api

COPY go.mod go.sum ./

RUN go mod download

# RUN go install github.com/air-verse/air@latest

COPY . .
RUN go mod tidy

# Build the Go app
RUN go build -o /app/cmd/main /app/cmd/main.go

# Expose port 3000 to the outside world
EXPOSE 3000

# Run the executable
CMD ["/app/cmd/main"]